Consid.ConferanceBooker/Controllers/ConferanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Consid.ConferanceBooker.Infrastructure;
using Newtonsoft.Json;
using Consid.ConferanceBooker.Models;
using Consid.ConferanceBooker.Models.CreateCalendarEvent;
using Consid.ConferanceBooker.Models.Arne;
using System.Globalization;

namespace Consid.ConferanceBooker.Controllers
{
    public class ConferanceController : Controller
    {

        

        [HttpGet]
        [Route("Index")]
        public async Task<IActionResult> Index()
        {
            ViewBag.KonferansRum = DataHolder.Instance.ConferanceName;

            return View("ListTodaysBookings");
        }



        [HttpGet]
        [Route("GetEvents")]
        public async Task<JsonResult> GetTodaysEvents()
        {
            try
            {
                DateTime startDate = DateTime.Now.AddHours(-2);
                DateTime endDate = DateTime.Now.AddDays(30).Date;

                var calenderView = await RequestHelper.GetCalendarViewAsync(startDate, endDate);

                if (!string.IsNullOrEmpty(calenderView))
                {
                    var calendarViewResult = JsonConvert.DeserializeObject<CalendarView>(calenderView);

                    

                    if (calendarViewResult != null && calendarViewResult.value != null && calendarViewResult.value.Any())
                    {


                        foreach (var row in calendarViewResult.value)
                        {
                           string tz = "W. Europe Standard Time";

                            TimeZoneInfo cstZone = TimeZoneInfo.FindSystemTimeZoneById(tz);
                            row.Start.DateTime = TimeZoneInfo.ConvertTimeFromUtc(row.Start.DateTime, cstZone);
                            row.End.DateTime = TimeZoneInfo.ConvertTimeFromUtc(row.End.DateTime, cstZone);
                        }

                        var calendarViewSortedAndAccepted = calendarViewResult
                            .value
                            .Where(X => X.ResponseStatus.Response.ToUpper() == "Accepted".ToUpper() || X.ResponseStatus.Response.ToUpper() == "Organizer".ToUpper())
                            .OrderBy(X => X.Start.DateTime)
                            .Take(10)
                            .ToList();

                        DataHolder.Instance.CurrentCalendarEvents = calendarViewSortedAndAccepted;

                        return Json(JsonConvert.SerializeObject(calendarViewSortedAndAccepted));
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }

            return Json("");
        }

        [HttpPut]
        [Route("CreateEvent")]
        public async Task<CreateCalendarEventResponse> CreateEvent()
        {         
            
            try
            {
                string tz = TimeZone.CurrentTimeZone.StandardName;
                var currentCalendarViewFirst = DataHolder.Instance.CurrentCalendarEvents.FirstOrDefault();
                DateTime? nextEvent = currentCalendarViewFirst?.Start.DateTime;
                var request = new CreateCalendarRequest();
                request.Start = new Models.Arne.Start();
                request.Start.DateTime = DateTime.Now;
                request.Start.TimeZone = tz;
                request.Subject = "Booked by PI";
                request.Body = new Body()
                {
                    Content = "Booked by pi",
                    ContentType = "text"
                };
                request.Attendees = new List<Attendee>()
                {
                    new Attendee()
                    {
                        EmailAddress = new Emailaddress1()
                        {
                            Address = DataHolder.Instance.EmailAddress,
                            Name =  DataHolder.Instance.ConferanceName
                        }
                    }
                }.ToArray();

                if (nextEvent == null)
                {                 
                    request.End = new Models.Arne.End()
                    {
                        DateTime = DateTime.Now.AddHours(1),
                        TimeZone = tz
                    };                  
                }
                else
                {
                    DateTime endDate = DateTime.Now.AddHours(1);
                    if(endDate > nextEvent.Value.AddMinutes(-1))
                    {
                        endDate = nextEvent.Value.AddMinutes(-1);
                    }

                    request.End = new Models.Arne.End()
                    {
                        DateTime = endDate,
                        TimeZone = tz
                    };                   
                }

               
                var createCalendarEventResponse = await RequestHelper.CreateEvent(request);
                return createCalendarEventResponse;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }

            return new CreateCalendarEventResponse();
        }

      public static DateTime UnixTimeStampToDateTime( double unixTimeStamp )
        {
            // Unix timestamp is seconds past epoch
            System.DateTime dtDateTime = new DateTime(1970,1,1,0,0,0,0,System.DateTimeKind.Utc);
            dtDateTime = dtDateTime.AddSeconds( unixTimeStamp ).ToUniversalTime();
            return dtDateTime;
        }

        public static DateTime JavaTimeStampToDateTime( double javaTimeStamp )
        {
            // Java timestamp is milliseconds past epoch
            System.DateTime dtDateTime = new DateTime(1970,1,1,0,0,0,0,System.DateTimeKind.Utc);
            dtDateTime = dtDateTime.AddMilliseconds( javaTimeStamp ).ToUniversalTime();
            return dtDateTime;
        }


        [HttpPut]
        [Route("Create")]
        public async Task<CreateCalendarEventResponse> CreateEvent(double start, double end)
        {

            try
            {
                DateTime startTime = JavaTimeStampToDateTime(start);
                DateTime endTime = JavaTimeStampToDateTime(end);
                string tz = TimeZone.CurrentTimeZone.StandardName;


                if (startTime != DateTime.MinValue && endTime != DateTime.MinValue)
                {
                    var currentCalendarViewFirst = DataHolder.Instance.CurrentCalendarEvents.FirstOrDefault();
                    DateTime? nextEvent = currentCalendarViewFirst?.Start.DateTime;

                  
                        var request = new CreateCalendarRequest();
                        request.Start = new Models.Arne.Start();
                        request.Start.DateTime = startTime;
                        request.Start.TimeZone = tz;
                        request.Subject = "Booked by PI";
                        request.Body = new Body()
                        {
                            Content = "Booked by pi",
                            ContentType = "text"
                        };
                        request.Attendees = new List<Attendee>()
                        {
                            new Attendee()
                            {
                                EmailAddress = new Emailaddress1()
                                {
                                    Address = DataHolder.Instance.EmailAddress,
                                    Name = DataHolder.Instance.ConferanceName
                                }
                            }
                        }.ToArray();

                        request.End = new Models.Arne.End()
                        {
                            DateTime = endTime,
                            TimeZone = tz
                        };


                        var createCalendarEventResponse = await RequestHelper.CreateEvent(request);
                        return createCalendarEventResponse;
                    
                }

                throw new Exception("Invalid dates!");
               
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }

            return new CreateCalendarEventResponse();
        }


    }
}

Consid.ConferanceBooker/Views/Conferance/ListTodaysBookings - Copy.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>	
	
    <meta name="viewport" content="width=device-width" />
    <title>Conferance booker</title>
	<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>	
	<script type="text/javascript" src="~/Scripts/Conferance.js"></script>	
	<link href="~/CSS/bootstrap-datetimepicker.min.css" rel="stylesheet" />
	<script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
</head>
<body>

	<div class="container">	
		<div id="bookingsListContainer">
			<h2 class="sub-header">Framtida bokningar i @ViewBag.KonferansRum</h2>
			<div class="table-responsive">
				<table id="eventTable" class="table table-striped">
					<thead>
						<tr>
							<th>Från</th>
							<th>Till</th>
							<th>Bokad Av</th>
						</tr>
					</thead>
					<tbody></tbody>
				</table>
			</div>
		</div>
	   <button class="btn btn-lg btn-primary btn-block" id="btnNewBooking" onclick="ConferanceCreator('@Url.Action("CreateEvent", "Conferance")')">Boka nu upp till en timmme reservas</button>	

		
		</div>
	 <!-- /container -->
	

</body>
</html>

<script>
	var getEventUrl = "@Url.Action("GetTodaysEvents", "Conferance")";
	var createEventUrl = "@Url.Action("CreateEvent", "Conferance")";

	Initiate(getEventUrl, createEventUrl);
</script>

Consid.ConferanceBooker/Views/Conferance/ListTodaysBookings.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
		  crossorigin="anonymous">
	<link rel="stylesheet" href="~/CSS/style.css">
	<link href="https://fonts.googleapis.com/css?family=Montserrat:600" rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>

	<title>LedigBoka</title>
</head>
<body>
	<div class="container-fluid full">
		<div class="top">
			<div class="row space  ">
				<div class="col-xs-10 ">
				</div>
				<div class="col-xs-2 text-right ">
					<span class="nu">nu</span>
					<span class="clock" id="time"></span>
				</div>
			</div>
			<div class="row ">
				<div class="col text-center  ">
					<h1 id="roomState">Ledig</h1>
				</div>
			</div>
		</div>
		<div class="row timemoments ">

			<div class="col-xs-3 text-center ">

				<div id="momentBtn1" class="timebtn1">
					<span></span>

				</div>
			</div>
			<div class="col-xs-3 text-center">
				<div id="momentBtn2" class="timebtn2">
					<span></span>
				</div>
			</div>
			<div class="col-xs-3 text-center">
				<div id="momentBtn3" class="timebtn3">
					<span></span>
				</div>
			</div>
			<div class="col-xs-3 text-center">
				<div id="momentBtn4" class="timebtn4">
					<span></span>
				</div>
			</div>

		</div>
		<div class="row ">
			<div class="col text-center ledigBokatidbtn">
				<button type="button" class="btn btnBokaTid" id="bokaTid">BOKA TID</button></br></br></br></br>
				<div class="medelande">Din tid är booked</div>
				<div class="medelande1">Välj tid först</div>
			</div>

		</div>
	</div>
	<script>
			   // var now = moment.utc().format('HH:mm:ss');
				//console.log(now);
	</script>
</body>
</html>
<script src="~/Scripts/plain.js"></script>